export const SET_LOADING_BUDGET = "SET_LOADING_BUDGET";
export const ERROR = "ERROR";

export const FETCH_BUDGET_SUCCESS = "FETCH_BUDGET_SUCCESS";
export const EDIT_BUDGET_SUCCESS = "EDIT_BUDGET_SUCCESS";

export const ADD_CATEGORY = "ADD_CATEGORY";
export const REMOVE_CATEGORY = "REMOVE_CATEGORY";

export const ADD_TRANSACTION = "ADD_TRANSACTION";
export const REMOVE_TRANSACTION = "REMOVE_TRANSACTION";
