export const SET_LOADING_BUDGET = 'SET_LOADING_BUDGET';
export const ERROR = 'ERROR';

export const FETCH_BUDGET_SUCCESS = 'FETCH_BUDGET_SUCCESS';

export const EDIT_BUDGET_SUCCESS = 'EDIT_BUDGET_SUCCESS';
// deleteT success
